// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVu7Y0a3QNbRuCnHrTTcdaEZHJFVKb8Go',
    appId: '1:78271867642:web:3769733d61db94c8ac3743',
    messagingSenderId: '78271867642',
    projectId: 'cudifire',
    authDomain: 'cudifire.firebaseapp.com',
    storageBucket: 'cudifire.appspot.com',
    measurementId: 'G-NL796LW2MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8zG52_cLOcVUQZ1GO_efytaxAElFWjEI',
    appId: '1:78271867642:android:3dafdd4bc2383bbdac3743',
    messagingSenderId: '78271867642',
    projectId: 'cudifire',
    storageBucket: 'cudifire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaXL0ODx7I_dfAR9DL33uHC3id0qiebF4',
    appId: '1:78271867642:ios:e701deed29607b7cac3743',
    messagingSenderId: '78271867642',
    projectId: 'cudifire',
    storageBucket: 'cudifire.appspot.com',
    iosBundleId: 'com.allrounder.cudi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaXL0ODx7I_dfAR9DL33uHC3id0qiebF4',
    appId: '1:78271867642:ios:dc184ea3d4ecd072ac3743',
    messagingSenderId: '78271867642',
    projectId: 'cudifire',
    storageBucket: 'cudifire.appspot.com',
    iosBundleId: 'com.example.cafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZPZXH6wq0NWOODzE_I2zXhowEW-3ba6c',
    appId: '1:78271867642:web:428432b0b138b42aac3743',
    messagingSenderId: '78271867642',
    projectId: 'cudifire',
    authDomain: 'cudifire.firebaseapp.com',
    storageBucket: 'cudifire.appspot.com',
    measurementId: 'G-BYHLBQ9CRK',
  );

}